spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.pstgprxisnjthgvthjao
spring.datasource.password=vnf42vnamwlqrv4c,mfyc.r,vhcgwx.kkciva
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Supabase
supabase.url=https://pstgprxisnjthgvthjao.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdGdwcnhpc25qdGhndnRoamFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MTAwMzEsImV4cCI6MjA4ODk4NjAzMX0.nXLYfnM8BUxFEE385CAbtvo2QtVRkYc8wPFlF82Dnxk
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://pstgprxisnjthgvthjao.supabase.co/auth/v1/.well-known/jwks.json