spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.pstgprxisnjthgvthjao
spring.datasource.password=vnf42vnamwlqrv4c,mfyc.r,vhcgwx.kkciva
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Supabase
supabase.url=https://pstgprxisnjthgvthjao.supabase.co
supabase.anon-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdGdwcnhpc25qdGhndnRoamFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MTAwMzEsImV4cCI6MjA4ODk4NjAzMX0.nXLYfnM8BUxFEE385CAbtvo2QtVRkYc8wPFlF82Dnxk
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://pstgprxisnjthgvthjao.supabase.co/auth/v1/.well-known/jwks.json

# i18n
spring.messages.encoding=UTF-8
spring.messages.basename=messages
spring.messages.fallback-to-system-locale=false

# Logging
logging.file.name=logs/application.log

# Tell Spring AI to use your Google AI Studio Key
spring.ai.vertex.ai.gemini.api-key="AIzaSyC8JvvZZfTQJJQPo4NRSS4wWzzfekAZuj8"

# Specify the model exactly as it appears (we'll try the flash one first as it's faster)
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash

# CRITICAL: Tell Vertex AI to use the generic endpoint, NOT a specific GCP project
spring.ai.vertex.ai.gemini.base-url=https://generativelanguage.googleapis.com/v1beta/models