name: Docker CD

on:
  workflow_run:
    workflows: ["Java CI"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Download artifact from CI
      - name: Download Spring Boot jar
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: maven-basic-project/target/
          run-id: ${{ github.event.workflow_run.id }}

      # 3. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}:latest \
            -f maven-basic-project/Dockerfile maven-basic-project

      # 5. Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest